version: '3'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
       - 'pgdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    restart: 'unless-stopped'

  redis:
    container_name: 'redis-stack'
    image: 'redis/redis-stack'
    volumes:
      - './redis:/var/lib/redis'
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: 'unless-stopped'

  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:management'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'

volumes:
    pgdata: