version: "3"
name: rabbitmq
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: "unless-stopped"
