version: "3"
name: redis
services:
  redis:
    container_name: "redis-stack"
    image: "redis/redis-stack"
    volumes:
      - "./redis:/var/lib/redis"
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: "unless-stopped"
