version: "3"
name: seq
services:
  seq:
    image: datalust/seq
    ports:
      - 8003:80
      - 5341:5341
    volumes:
      - /data/seq:/data
    environment:
      ACCEPT_EULA: "Y"
    restart: "unless-stopped"
